---

############################################################################################################################
################################################ INFORMATION ################################################################
############################################################################################################################

# All file paths accept absolute and relative paths
# Environment variables (including ~) are not processed, so don't use them in this config.


############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################

BASE_OUTPUT_DIR: /scratch/ben/CELLECT-LDSC-benchmark_runtime # for currect working directory use: ./CELLECT-LDSC
# Folder where all the output is saved (LD scores, prioritization results files, etc.) Directory will be created if it does not exists.
  

### SPECIFICITY_INPUT: list of dictionaries
# id: identifier for the dataset. Output files will be prefixed with the id. MUST be unique and NO double underscores allowed
# path: the path to the matrix containing specificity scores for each genomic region, does not need to be unique
SPECIFICITY_INPUT:
  - id: tabula_muris-spec-matrix-190811_subset
    path: /home/cbmr/xbq246/20190806-cellect/tabula_muris-spec-matrix-190811_subset.csv.gz
 # - id: mousebrain-test
 #  path: example/mousebrain-test.csv.gz # 2 annotations
 # - id: tabula_muris-test
 #   path: example/tabula_muris-test.csv # 5 annotations
#SPECIFICITY_INPUT:
#  - id: mousebrain
#    path: /projects/timshel/sc-genetics/timshel-bmicelltypes2019/out/es/mousebrain.mu.csv.gz
#  - id: tabula_muris
#    path: /projects/timshel/sc-genetics/timshel-bmicelltypes2019/out/es/tabula_muris.mu.csv.gz
#  - id: campbell2017_lvl2
#    path: /projects/timshel/sc-genetics/timshel-bmicelltypes2019/out/es/campbell2017_lvl2.mu.csv.gz
#  - id: modules.mousebrain_bmicelltypes
#    path: /projects/timshel/sc-genetics/timshel-bmicelltypes2019/out/wgcna/modules.mousebrain_bmicelltypes.specificity_human.csv.gz




### GWAS_SUMSTATS: list of dictionaries
# id: identifier for GWAS. MUST be unique and NO double underscores allowed
# path: filepath for munged GWAS sumstats.
# OBS: sumstats MUST be munged using the munge_sumstats.py script found in the LDSC repo.


# Trying out Pascal's GWAS collection
GWAS_SUMSTATS:
  - id: EA3_Lee2018
    path: /projects/alegbe/CELLECT-data/gwas/EA3_Lee2018.sumstats.gz 
  - id: BMI_Yengo2018
    path: /projects/alegbe/CELLECT-data/gwas/BMI_Yengo2018.sumstats.gz 

#GWAS_SUMSTATS:
#  - id: AD_Jansen2019
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/AD_Jansen2019.sumstats.gz
#  - id: ADHD_PGC_Demontis2017
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/ADHD_PGC_Demontis2017.sumstats.gz
#  - id: AN_PGC_Duncan2017
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/AN_PGC_Duncan2017.sumstats.gz
#  - id: ASD_iPSYCH_PGC_Grove2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/ASD_iPSYCH_PGC_Grove2018.sumstats.gz
#  - id: BIP_PGC2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/BIP_PGC2018.sumstats.gz
#  - id: BMI_Locke2015
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/BMI_Locke2015.sumstats.gz
#  - id: BMI_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/BMI_UKBB_Loh2018.sumstats.gz
#  - id: BMI_UPDATE_Yengo2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/BMI_UPDATE_Yengo2018.sumstats.gz
#  - id: CAD_Schunkert2011
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/CAD_Schunkert2011.sumstats.gz
#  - id: CARDIOVASCULAR_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/CARDIOVASCULAR_UKBB_Loh2018.sumstats.gz
#  - id: CELIAC_Dubois2010
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/CELIAC_Dubois2010.sumstats.gz
#  - id: CROHNS_Jostins2012
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/CROHNS_Jostins2012.sumstats.gz
#  - id: DEPRESSED_AFFECT_Nagel2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/DEPRESSED_AFFECT_Nagel2018.sumstats.gz
#  - id: DEPRESSION_Nagel2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/DEPRESSION_Nagel2018.sumstats.gz
#  - id: DIASTOLICadjMED_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/DIASTOLICadjMED_UKBB_Loh2018.sumstats.gz
#  - id: DS_Okbay2016
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/DS_Okbay2016.sumstats.gz
#  - id: EA2_Okbay2016
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/EA2_Okbay2016.sumstats.gz
#  - id: EA3_Lee2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/EA3_Lee2018.sumstats.gz
#  - id: FG_Female_Lagou2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/FG_Female_Lagou2018.sumstats.gz
#  - id: FI_Female_Lagou2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/FI_Female_Lagou2018.sumstats.gz
#  - id: HBA1C_MAGIC_Wheeler2017
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/HBA1C_MAGIC_Wheeler2017.sumstats.gz
#  - id: HEIGHT_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/HEIGHT_UKBB_Loh2018.sumstats.gz
#  - id: HEIGHT_Yengo2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/HEIGHT_Yengo2018.sumstats.gz
#  - id: IBD_Jostins2012
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/IBD_Jostins2012.sumstats.gz
#  - id: INSOMNIA_Jansen2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/INSOMNIA_Jansen2018.sumstats.gz
#  - id: INTELLIGENCE_Savage2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/INTELLIGENCE_Savage2018.sumstats.gz
#  - id: INTELLIGENCE_Sniekers2017
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/INTELLIGENCE_Sniekers2017.sumstats.gz
#  - id: LIPIDS_HDL_Teslovich2010
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/LIPIDS_HDL_Teslovich2010.sumstats.gz
#  - id: LIPIDS_LDL_Teslovich2010
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/LIPIDS_LDL_Teslovich2010.sumstats.gz
#  - id: LIPIDS_TG_Teslovich2010
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/LIPIDS_TG_Teslovich2010.sumstats.gz
#  - id: LUPUS_Bentham2015
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/LUPUS_Bentham2015.sumstats.gz
#  - id: MDD_Howard2019
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/MDD_Howard2019.sumstats.gz
#  - id: MDD_PGC_Wray2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/MDD_PGC_Wray2018.sumstats.gz
#  - id: MS_Patsopoulos2011
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/MS_Patsopoulos2011.sumstats.gz
#  - id: NEUROTICISM_Nagel2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/NEUROTICISM_Nagel2018.sumstats.gz
#  - id: NEUROTICISM_Okbay2016
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/NEUROTICISM_Okbay2016.sumstats.gz
#  - id: PBC_Cordell2015
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/PBC_Cordell2015.sumstats.gz
#  - id: RA_Okada2014
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/RA_Okada2014.sumstats.gz
#  - id: RB_Linner_2019
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/RB_Linner_2019.sumstats.gz
#  - id: SCZ_EUR_Ripke2014
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/SCZ_EUR_Ripke2014.sumstats.gz
#  - id: SCZ_Pardinas2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/SCZ_Pardinas2018.sumstats.gz
#  - id: SWB_Okbay2016
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/SWB_Okbay2016.sumstats.gz
#  - id: SYSTOLICadjMED_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/SYSTOLICadjMED_UKBB_Loh2018.sumstats.gz
#  - id: T1D_Bradfield2011
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/T1D_Bradfield2011.sumstats.gz
#  - id: T2D_DIAMANTE_Mahajan2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/T2D_DIAMANTE_Mahajan2018.sumstats.gz
#  - id: T2D_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/T2D_UKBB_Loh2018.sumstats.gz
#  - id: UC_Jostins2012
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/UC_Jostins2012.sumstats.gz
#  - id: WHR_Pulit2019
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/WHR_Pulit2019.sumstats.gz
#  - id: WHRadjBMI_Pulit2019
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/WHRadjBMI_Pulit2019.sumstats.gz
#  - id: WHRadjBMI_UKBB_Loh2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/WHRadjBMI_UKBB_Loh2018.sumstats.gz
#  - id: WORRY_Nagel2018
#    path: /projects/timshel/data/gwas_sumstats_ldsc/timshel-collection/WORRY_Nagel2018.sumstats.gz


ANALYSIS_TYPE: # specify what analysis modes to run. At least one mode needs to be specified.
  prioritization: True # prioritizes all cell-type annotations in the SPECIFICITY_INPUT datasets
  conditional: True # performs conditional analysis for selected annotations.
  heritability: True # estimates heritability for selected annotations.
  heritability_intervals: True # estimates heritability intervals for selected annotations. 'heritability' must be True when enabling heritability_intervals


WINDOW_DEFINITION: # Window definition for mapping gene specificity values to SNPs
  WINDOW_SIZE_KB:
    100
  WINDOW_LD_BASED: # Will override WINDOW_SIZE_KB if True. If True, use LD-based 'window' to map SNPs to genes. 
    False


############################################################################################################################
############################################## conditional analysis ########################################################
############################################################################################################################

### CONDITIONAL_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to condition on
# NOTE: you can delete or leave these dicts blank if 'mode' is not activated
CONDITIONAL_INPUT:
  - id: tabula_muris-spec-matrix-190811_subset
    annotations: ['Fat.T_cell', 
                  'Pancreas.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Brain_Non-Myeloid.oligodendrocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Skin.keratinocyte_stem_cell',
                  'Skin.leukocyte', 
                  'Limb_Muscle.endothelial_cell']
  #- id: mousebrain-test
  #  annotations: ['ABC']
  # - id: tabula_muris-test
  #   annotations: ['XX']


############################################################################################################################
############################################## heritability analysis ########################################################
############################################################################################################################

### HERITABILITY_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to estimate heritability for
# NOTE: you can delete or leave these dicts blank if 'mode' is not activated
HERITABILITY_INPUT:
  - id: tabula_muris-spec-matrix-190811_subset
    annotations: ['Fat.T_cell', 
                  'Pancreas.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Brain_Non-Myeloid.oligodendrocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Skin.keratinocyte_stem_cell',
                  'Skin.leukocyte', 
                  'Limb_Muscle.endothelial_cell']




############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################

# You generally do not need to change these variables.

LDSC_CONST:
  DATA_DIR: # Path to the data used for CELLECT-LDSC (baseline model, gene mapping etc).
    data/ldsc
  LDSC_DIR: # Path to the a cloned version of the github repo pascaltimshel/ldsc. This is included as a git submodule.
    /projects/alegbe/ldsc
    #ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1
