---

############################################################################################################################
################################################ INFORMATION ################################################################
############################################################################################################################

# All file paths accept absolute and relative paths
# Environment variables (including ~) are not processed, so don't use them in this config.


############################################################################################################################
############################################ RUN SPECIFIC VARIABLES ########################################################
############################################################################################################################

BASE_OUTPUT_DIR: /scratch/ben/CELLECT-LDSC-benchmark_runtime # for currect working directory use: ./CELLECT-LDSC
# Folder where all the output is saved (LD scores, prioritization results files, etc.) Directory will be created if it does not exists.
  

### SPECIFICITY_INPUT: list of dictionaries
# id: identifier for the dataset. Output files will be prefixed with the id. MUST be unique and NO double underscores allowed
# path: the path to the matrix containing specificity scores for each genomic region, does not need to be unique
SPECIFICITY_INPUT:
  - id: tabula_muris-spec-matrix-190811_subset
    path: /home/cbmr/xbq246/20190806-cellect/tabula_muris-spec-matrix-190811_subset.csv.gz
  # - id: mousebrain-test
  #  path: example/mousebrain-test.csv.gz # 2 annotations
  # - id: tabula_muris-test
  #   path: example/tabula_muris-test.csv # 5 annotations


### GWAS_SUMSTATS: list of dictionaries
# id: identifier for GWAS. MUST be unique and NO double underscores allowed
# path: filepath for munged GWAS sumstats.
# OBS: sumstats MUST be munged using the munge_sumstats.py script found in the LDSC repo.
GWAS_SUMSTATS:
  - id: EA3_Lee2018
    path: /projects/alegbe/CELLECT-data/gwas/EA3_Lee2018.sumstats.gz 
  #- id: BMI_Yengo2018
  #  path: /home/cbmr/jcd517/alegbe-projects/CELLECT-data/gwas/BMI_Yengo2018.sumstats.gz 


ANALYSIS_TYPE: # specify what analysis modes to run. At least one mode needs to be specified.
  prioritization: True # prioritizes all cell-type annotations in the SPECIFICITY_INPUT datasets
  conditional: True # performs conditional analysis for selected annotations.
  heritability: True # estimates heritability for selected annotations.
  heritability_intervals: False # estimates heritability intervals for selected annotations. 'heritability' must be True when enabling heritability_intervals


WINDOW_DEFINITION: # Window definition for mapping gene specificity values to SNPs
  WINDOW_SIZE_KB:
    100
  WINDOW_LD_BASED: # Will override WINDOW_SIZE_KB if True. If True, use LD-based 'window' to map SNPs to genes. 
    False


############################################################################################################################
############################################## conditional analysis ########################################################
############################################################################################################################

### CONDITIONAL_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to condition on
# NOTE: you can delete or leave these dicts blank if 'mode' is not activated
CONDITIONAL_INPUT:
  - id: tabula_muris-spec-matrix-190811_subset
    annotations: ['Fat.T_cell', 
                  'Pancreas.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Brain_Non-Myeloid.oligodendrocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Skin.keratinocyte_stem_cell',
                  'Skin.leukocyte', 
                  'Limb_Muscle.endothelial_cell']
  #- id: mousebrain-test
  #  annotations: ['ABC']
  # - id: tabula_muris-test
  #   annotations: ['XX']


############################################################################################################################
############################################## heritability analysis ########################################################
############################################################################################################################

### HERITABILITY_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to estimate heritability for
# NOTE: you can delete or leave these dicts blank if 'mode' is not activated
HERITABILITY_INPUT:
  - id: tabula_muris-spec-matrix-190811_subset
    annotations: ['Fat.T_cell', 
                  'Pancreas.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Brain_Non-Myeloid.oligodendrocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Tongue.keratinocyte',
                  'Mammary_Gland.endothelial_cell', 
                  'Skin.keratinocyte_stem_cell',
                  'Skin.leukocyte', 
                  'Limb_Muscle.endothelial_cell']




############################################################################################################################
################################################## CONSTANTS ###############################################################
############################################################################################################################

# You generally do not need to change these variables.

LDSC_CONST:
  DATA_DIR: # Path to the data used for CELLECT-LDSC (baseline model, gene mapping etc).
    data/ldsc
  LDSC_DIR: # Path to the a cloned version of the github repo pascaltimshel/ldsc. This is included as a git submodule.
    /projects/alegbe/ldsc
    #ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1
